--[[
    This script is the 2nd piece of code to run in the internal Lua VM. The
    API module is run first and inserts itself into `package.loaded`. This
    script is then called, and it in turn requires the user's `init.lua` to
    load their configuration.
]]

local autogen_notice = [[
Your configuration file is autogenerated!

You can remove this notice by opening it in a text
editor and following the instructions in the file.
]]

local default_config = [[
-- This configuration file was auto-generated by waywall. Refer to the
-- documentation for more information on how to configure waywall!
--
-- To remove the auto-generated notice, delete the 'config.autogen = true'
-- line at the bottom of the file.

local waywall = require("waywall")
local helpers = require("waywall.helpers")

local config = {
    theme = {
        background = "#303030ff",
    },
}

config.actions = {}

config.autogen = true -- Delete me to remove the auto-generated notice

return config
]]

--[[
    Setup the environment for the user's configuration.
]]

local priv = _G.priv_waywall

-- User code should not have access to private Lua API functions.
_G.priv_waywall = nil

-- The load* functions can be used to circumvent security measures in LuaJIT.
_G.load = nil
_G.loadfile = nil
_G.loadstring = nil

-- Do not load the ffi and jit extensions.
package.preload["ffi"] = nil
package.loaded["jit"] = nil

-- pcall and xpcall must be overridden to prevent user code from accidentally
-- catching the "instruction count exceeded" debug hook error.
local orig_pcall = _G.pcall
_G.pcall = function(fn, ...)
    local ret = { orig_pcall(fn, ...) }

    if not ret[1] and ret[2] == "instruction count exceeded" then
        error("instruction count exceeded")
    end

    return unpack(ret)
end

local orig_xpcall = _G.xpcall
_G.xpcall = function(fn, msgh, ...)
    local ret = { orig_xpcall(fn, msgh, ...) }

    if not ret[1] and ret[2] == "instruction count exceeded" then
        error("instruction count exceeded")
    end

    return unpack(ret)
end

-- The print function is overridden to annotate calls to Lua print() in stdout.
_G.print = function(...)
    local str = nil
    for _, v in ipairs({ ... }) do
        if str then
            str = str .. " " .. tostring(v)
        else
            str = tostring(v)
        end
    end
    priv.log(str)
end

-- Lua does not provide a setenv function, so we do.
package.loaded["os"].setenv = priv.setenv

--[[
    Run the user's configuration.
]]

-- Setup the package path to include any valid waywall configuration
-- directories.
local get_config_dirs = function()
    local paths = {}

    local xdg_config_home = os.getenv("XDG_CONFIG_HOME")
    if not xdg_config_home or xdg_config_home:sub(1, 1) ~= "/" then
        local home = os.getenv("HOME")
        if not home then
            error("no $HOME or $XDG_CONFIG_HOME")
        end
        xdg_config_home = home .. "/.config"
    end
    table.insert(paths, xdg_config_home)

    local xdg_config_dirs = os.getenv("XDG_CONFIG_DIRS")
    if not xdg_config_dirs then
        table.insert(paths, "/etc/xdg")
        return paths
    end

    for path in xdg_config_dirs:gmatch("([^:]+)") do
        if path:sub(1, 1) == "/" then
            table.insert(paths, path)
        end
    end

    return paths
end

local config_dirs = get_config_dirs()
for _, dir in ipairs(config_dirs) do
    package.path = package.path .. ";" .. dir .. "/waywall/?.lua"
end

-- Run the user's configuration file. If it doesn't exist, then create a default
-- one for them.
local profile = priv.profile() or "init"

local function load_config(autogenerate)
    local ok, result = pcall(require, profile)

    if ok then
        if type(result) == "table" then
            print("loaded configuration from profile '" .. profile .. "'")
            return result
        end

        error("expected table from user configuration, got " .. type(result))
    else
        if result:find("not found:") then
            if not autogenerate then
                error(result)
            end

            print(
                "failed to find configuration file (profile = '"
                    .. profile
                    .. "', package.path = '"
                    .. package.path
                    .. "')"
            )

            local path = assert(config_dirs[1], "no config dirs") .. "/waywall/"
            os.execute("mkdir -p " .. path)
            path = path .. profile .. ".lua"
            local file, err = io.open(path, "a+")
            if err then
                error("failed to auto-generate a configuration file: " .. err)
            end
            file:write(default_config)
            file:close()

            print("auto-generated configuration file at " .. path)

            -- Try loading the new auto-generated configuration. Do not try to
            -- generate a new one if somehow loading the configuration still
            -- fails.
            return load_config(false)
        else
            error(result)
        end
    end
end

local user_config = load_config(true)

if user_config.autogen then
    -- selene: allow(unused_variable)
    local autogen_text = nil

    local waywall = require("waywall")
    waywall.listen("load", function()
        autogen_text = waywall.text(autogen_notice, { x = 10, y = 10, size = 1 })
    end)
end

return user_config
